### ISSUE TITLE
Make the wavedrom link configurable

### ISSUE THREAD

**Issue by wifasoi** [bavovanachte/sphinx-wavedrom#10]
As I understand, the wavedrom link to the JavaScript file is hard-coded.
I had a recent issue with github page that can't render the wavedrom diagram (mixed content error -> try to download http content in a https page).
There are several work-arround (offline wavedrom), but i think the best way is to leave the user specify (if needed) the link to the necessary scripts in the conf.py.

**Comment by wifasoi** [comment]
not rush. If I have some time I can tackle this problem (and create a PR).

**Comment by bavovanachte** [comment]
Proposal in #25

**Comment by wifasoi** [comment]
#25 does work wonder (i can use the cdn version of wavedrom, so that's a plus :) )
(for future references: this will not fix the github pages problem, because link from the auto will redirect to the http version, but at least now you can self host it and fix it in this way)

**Comment by bavovanachte** [comment]
I'm not entirely sure what the github pages issue is exactly. Is it something that can be fixed on plugin side?

**Comment by bavovanachte** [comment]
And thanks for trying it out!

**Comment by wifasoi** [comment]
> Is` it something that can be fixed on plugin side?
Don't think so, the fix is to self host an https version. Or ask kindly @Drom to host an https version of the js scripts (and not redirect it and strip the https).
Anyway, now i have the option. Thank you for your work :)

**Comment by drom** [comment]
What is exactly the issue here? Have you tried CDN?
https://github.com/wavedrom/wavedrom#html-pages

**Comment by wifasoi** [comment]
Ahaa, sorry for the mention @drom .
I tried with the cdn, and it trigger the cross origin error (the cdn will return the java script from an http source).
Maybe I can open an issue on your project (with proper screenshot), Instead of whine behind your back :)

**Comment by drom** [comment]
it might be a CDN issue: https://github.com/cdnjs/cdnjs
