### ISSUE TITLE
Support for bit fields

### ISSUE THREAD

**Issue by wifasoi** [bavovanachte/sphinx-wavedrom#11]
Before 2.0 you can use the wavedrom bitfield extension. Now we are limited by the capability of wavedrompy (no problem for me)
This is just a reminder that this feature will be available to us when the https://github.com/BreizhGeek/wavedrompy/pull/7 will be merged

**Comment by wallento** [comment]
Hi,

you can still use bitfield for the online js version, wavedrompy is not necessary.

Anyhow, wavedrompy supports bitfields now (also schematics), but unfortunately it didn't get merged into the original repo so far. But I have uploaded my latest version to pypi as release candidate. Can you please try that?

Cheers,
Stefan

**Comment by wifasoi** [comment]
Ahh ok, didn't know you added the bit extension to your fork, cool.
I'll test the release candidate right now, but For future reference down here the stack-trace.

Maybe is a problem with ReadTheDoc, but this is the error that trow me:
https://pastebin.com/QJv5eNVb

with this wavedrom snippet
```
.. wavedrom::

   {"reg":[
      {"bits": 8, "name": "things"},
      {"bits": 2, "name": "stuff" },
      {"bits": 6}
     ],
     "config": { "bits":16,"lanes":1 }
   }
```

**Comment by joshuascheid** [comment]
That's because the call to WaveDrom().renderWaveForm() returns None, since the data is not of "signal" type.  Either use a top-level "render" call like in 
https://github.com/wallento/wavedrompy/blob/master/wavedrom/__init__.py#L33
or duplicate that logic at
https://github.com/bavovanachte/sphinx-wavedrom/blob/master/sphinxcontrib/wavedrom.py#L137

**Comment by bavovanachte** [comment]
I'm assuming this fixes the issue reported by @wifasoi . Closing now, feel free to reopen if not the case
