### ISSUE TITLE
Graph is not drawing without name

### ISSUE THREAD

**Issue by kravchenkoloznia** [bavovanachte/sphinx-wavedrom#18]
If "name" field in wavedrom json file is empty that line of graph will not shown in pdf file.

In next example first line will not shown. But if add anything as a name it will start drawing correctly.

```
{ "signal": [
        { "name": "",  "wave": "x3...4.....|5...x", "data": ["16bit", "Nbit", "16bit"]},
        { "name": "b",  "wave": "x3...4.....|5...x", "data": ["header", "payload", "crc"]},
]}
```

![Screenshot_20190522_190254](https://user-images.githubusercontent.com/32360199/58190044-5bf92680-7cc4-11e9-9cea-b36a1594de78.png)

**Comment by JasperCraeghs** [comment]
This Sphinx plugin in its current state makes use of [wavedrompy](https://github.com/wallento/wavedrompy) to generate the diagram for **pdf** files. Today the maintainer of wavedrompy released a fix for the issue you posted. I reported the issue [here](https://github.com/wallento/wavedrompy/issues/9). Please install [wavedrom>=2.0.2](https://pypi.org/project/wavedrom/2.0.3/).

`pip install wavedrom==2.0.3`

**Comment by bavovanachte** [comment]
Thanks @JasperCraeghs ! Closing now.
