### ISSUE TITLE
Latest Wavedrom release (v2.0.0) broken with Sphinx v3.0

### ISSUE THREAD

**Issue by mvanrompuy** [bavovanachte/sphinx-wavedrom#21]
Yesterday Sphinx released v3.0 which removes support for 'copy_static_entry'  from 'sphinx.util'. The latest pypi build of sphinx-wavedrom still uses these function and is now broken when using the latest sphinx release.

The dependency on this function was already removed in issue #16, but no official release of this tool was made since that change.

Can a new pypi package be created which includes (at least) this fix?

**Comment by tschinz** [comment]
+1

**Comment by mvanrompuy** [comment]
Current workaround for me (proving that latest repo state does work with Sphinx v3.0):
pip install git+https://github.com/bavovanachte/sphinx-wavedrom.git@81774d64f45253453b45641cbb84f964516094fe

**Comment by bavovanachte** [comment]
Thanks for reporting! I'll make a new release

**Comment by tschinz** [comment]
I can confirm it works. Thanks for the new release and the plugin

**Comment by mvanrompuy** [comment]
Also works for me. Thanks for the quick response!
