### ISSUE TITLE
Adding optional scrollbars to the waveform

### ISSUE THREAD

**Issue by Paebbels** [bavovanachte/sphinx-wavedrom#3]
Hello,

is it possible to put the waveform into a div-box with optional scrollbars?

![image](https://cloud.githubusercontent.com/assets/956109/20479224/ba10d972-afdd-11e6-9532-1f6b56f071bc.png)

**Comment by bavovanachte** [comment]
Interesting. I'll try to play around a bit to see if I can come up with something.

**Comment by bavovanachte** [comment]
Any help is welcome, though :smirk:

**Comment by bavovanachte** [comment]
Could you check whether #4 is what you're looking for? You can build the example to check

**Comment by Paebbels** [comment]
I have tested your new branch. It looks good. So I think you can bundle your changes for PIP :).
Thanks!

**Comment by bavovanachte** [comment]
Done. Version 1.3.0 is on pip. Enjoy!
