### ISSUE TITLE
Followup from #8: align version of wavedrompy and the embedded js files

### ISSUE THREAD

**Issue by bavovanachte** [bavovanachte/sphinx-wavedrom#9]
_Originally posted by @bavovanachte in https://github.com/bavovanachte/sphinx-wavedrom/pull/8#issuecomment-441351963_

We should make sure that the js files embedded here are not lagging behind the version that is implemented by wavedrompy plugin

**Comment by bavovanachte** [comment]
FYA @wallento

**Comment by wallento** [comment]
I assume it makes sense to keep the version numbers in sync, too.

(Fortunately) wavedrom doesn't change this massively often. I will try to understand the differences between both this weekend and get them in-sync, so that js and wavedrompy should all be in sync with 1.6.3 soon.

**Comment by wallento** [comment]
1.8.0 I mean..

**Comment by wallento** [comment]
Okay, I started with a few minor patches for the actual waveform, should be done soon. There are two other json formats in wavedrom: schematics and register bitfields. Both are probably useful, but I am a bit undecided if its best to have them in the same package actually. What do you guys think?

**Comment by wallento** [comment]
FYI: I implemented the missing features today and pushed them to my fork. I plan to add proper tests and documentation before the PR. I think we are nearly on the same level as the javascript code!

**Comment by wallento** [comment]
Quick update: https://pypi.org/project/wavedrom/1.8.0rc3/

I think we are up-to-date with the official release now!

**Comment by bavovanachte** [comment]
Good news, thanks! I'm not sure why I said we have embedded js files in this plugin, we clearly don't (it's been a while since I've used it).

In your PR, could you add a note on where the non-js implementation comes from and what it's limitations are wrt the "official" implementation?
